<?php

namespace Database\Seeders;

use App\Models\LedgerAccount;
use App\Models\Organization;
use Illuminate\Database\Seeder;

class LedgerAccountSeeder extends Seeder
{
    /** @var list<array{code: string, name: string, account_type: string, normal_balance: string}> */
    private const array ACCOUNTS = [
        ['code' => '1000', 'name' => '現金及び預金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1010', 'name' => '現金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1020', 'name' => '当座預金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1030', 'name' => '普通預金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1100', 'name' => '売掛金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1110', 'name' => '受取手形', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1120', 'name' => '貸付金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1130', 'name' => '仮払金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1140', 'name' => '前払販売費', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1150', 'name' => '前払一般管理費', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1160', 'name' => '未収利息', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1170', 'name' => '未収収益', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1200', 'name' => '棚卸資産', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1210', 'name' => '商品', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1220', 'name' => '繰越商品', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1230', 'name' => '商品及び製品', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1300', 'name' => '貸倒引当金', 'account_type' => 'asset', 'normal_balance' => 'credit'],
        ['code' => '1510', 'name' => '建物', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1511', 'name' => '建物減価償却累計額', 'account_type' => 'asset', 'normal_balance' => 'credit'],
        ['code' => '1520', 'name' => '機械装置', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1521', 'name' => '機械装置減価償却累計額', 'account_type' => 'asset', 'normal_balance' => 'credit'],
        ['code' => '1530', 'name' => '工具器具備品', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1531', 'name' => '工具器具備品減価償却累計額', 'account_type' => 'asset', 'normal_balance' => 'credit'],
        ['code' => '1540', 'name' => '備品', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1541', 'name' => '備品減価償却累計額', 'account_type' => 'asset', 'normal_balance' => 'credit'],
        ['code' => '1550', 'name' => '土地', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1600', 'name' => 'ソフトウェア', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1610', 'name' => '商標権', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1620', 'name' => 'のれん', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1630', 'name' => '開発費', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1700', 'name' => '有価証券', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1710', 'name' => '投資有価証券', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1720', 'name' => '関係会社株式', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1730', 'name' => '長期貸付金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1740', 'name' => '長期定期預金', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1800', 'name' => '繰延税金資産', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1810', 'name' => '破産更生債権等', 'account_type' => 'asset', 'normal_balance' => 'debit'],
        ['code' => '1900', 'name' => '減価償却累計額', 'account_type' => 'asset', 'normal_balance' => 'credit'],

        ['code' => '2000', 'name' => '買掛金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2010', 'name' => '支払手形', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2020', 'name' => '仕入債務', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2100', 'name' => '未払金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2110', 'name' => '未払費用', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2120', 'name' => '未払一般管理費', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2130', 'name' => '未払法人税等', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2140', 'name' => '仮受金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2200', 'name' => '賞与引当金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2210', 'name' => '退職給付引当金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2220', 'name' => '製品保証引当金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2300', 'name' => '短期借入金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2400', 'name' => '借入金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2410', 'name' => '長期借入金', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2500', 'name' => '退職給付に係る負債', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2510', 'name' => '資産除去債務', 'account_type' => 'liability', 'normal_balance' => 'credit'],
        ['code' => '2600', 'name' => '繰延税金負債', 'account_type' => 'liability', 'normal_balance' => 'credit'],

        ['code' => '3000', 'name' => '資本金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3010', 'name' => '資本準備金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3020', 'name' => 'その他資本剰余金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3100', 'name' => '利益準備金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3200', 'name' => '利益剰余金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3210', 'name' => '繰越利益剰余金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3220', 'name' => '別途積立金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3230', 'name' => '圧縮積立金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3300', 'name' => '自己株式', 'account_type' => 'equity', 'normal_balance' => 'debit'],
        ['code' => '3400', 'name' => 'その他有価証券評価差額金', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3410', 'name' => '退職給付に係る調整累計額', 'account_type' => 'equity', 'normal_balance' => 'debit'],
        ['code' => '3420', 'name' => '退職給付に係る調整額', 'account_type' => 'equity', 'normal_balance' => 'debit'],
        ['code' => '3500', 'name' => '新株予約権', 'account_type' => 'equity', 'normal_balance' => 'credit'],
        ['code' => '3600', 'name' => '非支配株主持分', 'account_type' => 'equity', 'normal_balance' => 'credit'],

        ['code' => '4000', 'name' => '売上', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4010', 'name' => '製品売上', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4020', 'name' => '商品及び製品売上', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4100', 'name' => 'サービス売上', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4110', 'name' => '役務収益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4190', 'name' => 'その他の営業収益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4200', 'name' => '受取利息', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4210', 'name' => '受取利息及び配当金', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4220', 'name' => '有価証券運用損益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4230', 'name' => '投資有価証券評価損益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4240', 'name' => '為替差益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4250', 'name' => '転リース差益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4260', 'name' => '雑収益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4290', 'name' => 'その他の営業外収益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4300', 'name' => '固定資産売却益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4310', 'name' => '有価証券売却益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],
        ['code' => '4390', 'name' => 'その他の特別利益', 'account_type' => 'revenue', 'normal_balance' => 'credit'],

        ['code' => '5000', 'name' => '売上原価', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5010', 'name' => '製品売上原価', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5020', 'name' => '商品及び製品売上原価', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5030', 'name' => '役務原価', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5100', 'name' => '仕入', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5200', 'name' => '材料費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '5300', 'name' => 'ソフトウェア償却', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6000', 'name' => '給与手当', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6010', 'name' => '従業員賞与', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6020', 'name' => '法定福利費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6030', 'name' => '賞与引当金繰入額', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6040', 'name' => '退職給付費用', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6050', 'name' => '株式報酬費用', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6060', 'name' => '役員報酬', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6100', 'name' => '販売費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6110', 'name' => '一般管理費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6120', 'name' => 'その他の販売費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6130', 'name' => 'その他の一般管理費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6140', 'name' => 'その他の営業費用', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6150', 'name' => '広告宣伝費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6160', 'name' => '通信費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6170', 'name' => '地代家賃', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6180', 'name' => '消耗品費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6190', 'name' => '外注費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6200', 'name' => '貸倒引当金繰入額', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6210', 'name' => '製品保証引当金繰入額', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '6220', 'name' => '製品保証費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7000', 'name' => '減価償却費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7010', 'name' => '建物減価償却費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7020', 'name' => '備品減価償却費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7100', 'name' => '研究開発費', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7200', 'name' => '支払手数料', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7300', 'name' => '利息費用', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7400', 'name' => '支払利息', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7410', 'name' => '為替差損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7420', 'name' => '雑損失', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7490', 'name' => 'その他の営業外費用', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7500', 'name' => '投資有価証券評価損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7510', 'name' => '関係会社株式評価損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7520', 'name' => '固定資産売却損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7530', 'name' => '固定資産除却損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7540', 'name' => '有価証券売却損', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7550', 'name' => '減損損失', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7560', 'name' => '災害損失', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7590', 'name' => 'その他の特別損失', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7600', 'name' => '法人税、住民税及び事業税', 'account_type' => 'expense', 'normal_balance' => 'debit'],
        ['code' => '7610', 'name' => '法人税等調整額', 'account_type' => 'expense', 'normal_balance' => 'debit'],
    ];

    public function run(): void
    {
        Organization::query()->select('id')->eachById(function (Organization $organization): void {
            $now = now();
            $accounts = array_map(fn (array $account): array => [
                'organization_id' => $organization->id,
                ...$account,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ], self::ACCOUNTS);

            LedgerAccount::query()->upsert(
                $accounts,
                ['organization_id', 'code'],
                ['name', 'account_type', 'normal_balance', 'is_active', 'updated_at'],
            );
        });
    }
}
